### ISSUE TITLE
consolidate online and offline course themes

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-themes#1013]
Right now we have 3 main use cases for building a course site:
1. To be viewed online as part of [ocw.mit.edu](http://ocw.mit.edu/)
2. To be viewed offline (download version)
3. To create mirror drives (1 above, but offline)

Currently we have 2 themes related to building course sites: `course-v2`, `course-offline`:

 - `course-v2` allows us to accomplish item 1 from above
 - `course-offline` allows us to accomplish 2 and 3 from above

We have all these use cases covered, however, what we have done in `course-offline` is not optimal. We've split places where Hugo is rendering URLs into a set of partials that have a default in `base-theme` that are then [overridden in `course-offline`](https://github.com/mitodl/ocw-hugo-themes/tree/main/course-offline/layouts/partials). This was done to avoid having to change the way case 1 renders URLs while still creating a solution for 2 and 3. By default, Hugo renders links starting with a `/`, which are called "schemaless relative urls of subtype path-absolute" according to the [URL standard](https://url.spec.whatwg.org/#relative-url-string), and an offline site like 2 and 3 need relative URLs to work. Hugo also renders "clean" URLs by default and does not include `/index.html` when linking to pages, so this is appended to URLs in `course-offline`. Generally, this takes the approach of rewriting the URL to be relative during templating before Hugo renders the site as HTML.

The preferred approach for making a Hugo site browsable from the local file system, [according to the docs](https://gohugo.io/content-management/urls/#relative-urls), is to turn on the `relativeUrls` setting in the Hugo config file. This setting is a *post processing* feature that, after all the HTML is rendered, will crawl the site and rewrite URLs that it finds in a [specific set of attributes](https://github.com/gohugoio/hugo/blob/1477d0ba90acd3aa464556d95edab396a518016e/transform/urlreplacers/absurlreplacer.go#L68-L76). We should be using this setting to render our URLs as relative across the board, but there are a few things preventing us from simply turning the setting on:

 - https://github.com/mitodl/ocw-studio/issues/1664 is what we believe to be a bug with the `baseUrl` setting that causes how we use it to be incompatible with turning on `relativeUrls`
 - Links to shared static assets (JS, CSS, images) would be rendered incorrectly
 - Links to other courses would be rendered incorrectly
 - Links in the sitemaps would be rendered incorrectly
 - Hard coded links in shared partials such as `/about` in the header would be rendered incorrectly

My plan is to create 2 new themes called `course-v3` and `course-offline-v2` which will take `course-v2` and include only the UI overrides in `course-offline` in `course-offline-v2`. This will allow us to solve the above issues while removing the URL hacks in `course-offline` without disrupting sites that currently use `course-v2` and `course-offline`. In the end, we will use `course-v3` for all use cases above, removing the use of `baseUrl` in case 1. `course-offline-v2` will be used in case 2, but only to do things like hide the download button on the home page and course info drawer, which makes no sense to display in an already downloaded course.

```[tasklist]
### ocw-studio
- [x] https://github.com/mitodl/ocw-studio/issues/1648
- [ ] https://github.com/mitodl/ocw-studio/issues/1664
- [ ] https://github.com/mitodl/ocw-studio/issues/1667
```

```[tasklist]
### ocw-hugo-projects
- [ ] https://github.com/mitodl/ocw-hugo-projects/issues/239
- [ ] https://github.com/mitodl/ocw-hugo-projects/pull/244
```

```[tasklist]
### ocw-hugo-themes
- [x] https://github.com/mitodl/ocw-hugo-themes/issues/1055
- [ ] https://github.com/mitodl/ocw-hugo-themes/pull/1068
- [ ] more to come...
```

**Comment by gumaerc** [comment]
@Ferdi  I've been doing a bunch of testing today trying to consolidate the online / offline themes like we discussed. What I've found is that the situation with relative URLs is not as bad as I thought, but there are still some things to consider.

With `relativeURLs: true`, Hugo will only actually generate relative URLs when running the `hugo` command, not when running `hugo server`, but the relative URLs that it does generate with this setting are truly relative and even work with the string based `url` property of the nav menu that we write into `menus.yaml`. `relativeURLs: true` does *not* affect URLs inside of `<style>` or `<script>` tags. Right now for us there are a few places where this is an issue:
 - The URL to the Material Icons font files, which are loaded inside of a `<style>` tag
 - The URL passed to `PDFObject` for displaying inline PDF's, which is inside of a `<script>` tag

Hugo has a function called [`relURL`](https://gohugo.io/functions/relurl/) that can be used to generate relative URLs for situations such as these, but it requires two things. The first is, of course, the URL of the page / resource you want to link to. The second is the context of the page from which you are rendering said URL. You might notice that the context isn't an argument that's passed into the function, and that's because it's assumed to be the `.` object where the function is called. If you call a partial without any arguments, this `Page` context is sent as the default argument. A Hugo partial only takes one argument, but a lot of our partials need additional information to be passed so we use a technique where a `dict` object is passed, containing the `.` object mapped to `context` along with whatever else needs to be sent to that partial. Therefore, when you call `relURL` inside these partials, the `.` object is a `dict` and not a `Page` and the appropriate context cannot be determined. I'm looking into a way that we might be able to address this.

Another thing to consider are links outside of the context of a given course site, such as:
 - Links to JS / CSS bundles from the webpack build
 - Links to pages / resources in other courses

Say hypothetically we render a course for the live site with `--baseURL /courses/course-1`. If we were to relatively link to `/static/course.css` at the root of the site from the course home page, the resulting link would be `../../static/course.css`. If you then downloaded this course and tried to simply double click on the course home page HTML file, it would be trying to load the JS / CSS by stepping up 2 directories from the folder the course site is stored in. Likewise, if you were linking to a resource from another course the current way that is done is by writing in a root relative link in the markdown, for example `[Video](/courses/course-2/resources/video)`. If `relativeUrls: true` were enabled and this link were being rendered on a page at `/syllabus` with the same base URL, the resulting URL would be `../../../courses/course-2/resources/video`. These URLs would work in the live site, but not once you download the files.

Something I was thinking we might be able to try is to turn `relativeUrls: true` on, and then set up a fallback in Fastly for `**/static` to try fetching the file relative to the root of the site if the file cannot be found relative to the root of the course subfolder. I'm also still exploring other options we might have for dealing with these various issues, and will update this issue with whatever I find.

**Comment by gumaerc** [comment]
I worked on this more today and experimented with setting the `href` property on a `base` tag at the top of the `head` at runtime with the root URL of the site. Using this method, along with pulling in some of the things that the offline build does like relative URLs and automatically appending `/index.html` where appropriate, I was able to get a build going that behaves mostly the same between the dev server and double clicking any of the HTML files directly in the OS. I simulated a mass build in my local instance of `ocw-studio` and downloaded the results for one of the courses. Here are the remaining issues I found:

 - Even with full relative URLs throughout the entire site, simply downloading the HTML from the live site won't work because we are changing the relative relation of the HTML to what was considered the root of the site at build time based on `baseURL`. The problem remains that the URLs generated at build time for some items tries to step back 2 directories to get to the root of the live site:
   - JS / CSS bundles
   - Header / footer images like the OCW logo, Open Learning logo and social logos
   - Base theme images like expand / contract icons, etc.
   - Fonts
 - The sitemap still needs to use fully qualified URLs, but won't be used offline anyway so that's okay
 - Assuming we will still be creating ZIP files during the build, we will still need to include the following and the path will need to match the relative association on the live site:
   - The static assets listed above that are part of the theme
   - The static resources for the course (PDF's, images, etc.)

An idea that has been popping up in my head was that maybe we could utilize functionality in Fastly as a fallback to redirect to the above assets. Say we change the relative linking to not try and reach back to the root based on `baseUrl` and instead write in links relative to the course home page. These files don't exist in every course subfolder in the production S3 bucket, but maybe Fastly could redirect all requests to `/courses/course-1/static/*` to `/static/*`? I'm not sure what the impact of all that redirecting would be on performance, but I think it's worth investigating because it would make things significantly more simple. That way, we could have a `static` folder in the ZIP file containing all the resources necessary to run the site and the links would all "just work" locally, but then Fastly would handle sourcing them from the proper location in production.

**Comment by gumaerc** [comment]
@pdpinch This could potentially work, although the root folder would have to be "courses," with the rest of the directory structure you proposed under it. The static folder sits at the root so with relative URLs everywhere a reference to the CSS for example would look like `../../static/css/course_v2.69060.css` from the course home page. It would be a simple solution, but I don't like how it would make the ZIP archive kind of messy.

I did some more experimentation with this today using the nginx server in our `ocw-studio` Docker setup, and was able to get a course site that references the static folder relative to the course home page that works both on the web and offline with relative URLs using this simple redirect rule:

```
        # Rewrite requests to shared static assets to the root shared_static folder
        location ~ ^/courses/.*/static_shared/.* {
            rewrite ^/courses/.*/static_shared/(.*)$ /static_shared/$1 last;
        }
```

You'll notice that I also changed the name of the `static` folder to `static_shared`. This is to avoid any confusion and give us a place to explicitly put assets that are shared by all sites. If we could do something similar to the above in our Fastly configuration, then the reference to that CSS file (on the course home page, for example) could be written in as simply `./static_shared/css/course_v2.69060.css` and it would work both offline and online. You would of course need to put the `static_shared` folder inside every ZIP file, but the HTML from the live site could be used instead of having to maintain a separate offline theme. There are other things to consider that we'll have to deal with, such as the fact that the actual path to resources written into markdown by `ocw-studio` is absolute (including the `/courses/name` prefix). My plan for this was to change this so that all resources are placed in a `static_resources` folder and the URLs written into the markdown are relative, but I need to do more testing with that.

**Comment by pdpinch** [comment]
You are persuading me that the redirect approach is feasible, but I want to advocate my suggestion one more time -- what about pushing the `static` directory (which I agree should be renamed `static_shared` or something like that) down into the `course` directory?

**Comment by gumaerc** [comment]
Closing this issue as we have decided not to proceed with consolidating the online and offline themes and are keeping them separate, pursing a [mirror drive MVP](https://github.com/mitodl/hq/issues/785) by setting up separate buckets for the offline builds.
