### ISSUE TITLE
Accessibility issues related to <i> tags

### ISSUE THREAD

**Issue by ibrahimjaved12** [mitodl/ocw-hugo-themes#1223]
This epic lists down all the instances related to `i` tags where accessibility may not be handled or handled inconsistently (or redundantly). They need to be looked into to determine whether they're used in correct accessibility sense or not.

```[tasklist]
### Tasks
- [ ] https://github.com/mitodl/ocw-hugo-themes/issues/1218
- [ ] https://github.com/mitodl/ocw-hugo-themes/issues/1219
- [ ] https://github.com/mitodl/ocw-hugo-themes/issues/1220
- [ ] https://github.com/mitodl/ocw-hugo-themes/issues/1221
- [ ] https://github.com/mitodl/ocw-hugo-themes/issues/1222
```

Mainly we need to find the webpage what the codes are about, and then inspect the code from there. Also running screen reader on it is really helpful.

### Other info
This is a follow-up epic to the discussion in: https://github.com/mitodl/hq/issues/1918

**Comment by ibrahimjaved12** [comment]
Closing this as all the tasks are completed
