### ISSUE TITLE
CHP: Improve Lighthouse stats

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#618]
CHP performance and accessibility are in the yellow zone. 

See https://www.foo.software/dashboard/pages?pageId=6074b1ca0ed13f002507bc56

Some suggestions from Lighthouse:
- [ ] #636
- [ ] #649
- [ ] #634
- [ ] #648
- [ ] #650
- [x] https://github.com/mitodl/ocw-hugo-themes/issues/1038
- [x] https://github.com/mitodl/ocw-hugo-themes/issues/1035
- [x] https://github.com/mitodl/ocw-hugo-themes/issues/1033

**Comment by MAbdurrehman12** [comment]
I'm unable to access this link:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/93309234/162419487-063bae1d-c09a-46a7-ae2e-51689e86db04.png">

maybe you can add me as a user in `Account > Users` though I have created an account on [foo.software](https://www.foo.software/) and added a page `https://ocw.mit.edu/` and the stats which I'm seeing has `accessibility=100` though `performance`, `CLS`, `LCP` are in yellow zone and  `PWA` in red zone so I'll look into these.

**Comment by MAbdurrehman12** [comment]
I think, by doing the following, we can improve Performance (including CLS, FCP, LCP, TTI): 

1. Most important: Change the image formats to nextgen formats, i.e: WebP and AVIF ([reference](https://web.dev/uses-webp-images/?utm_source=lighthouse&utm_medium=node)). Browser compatibility might be an issue so in that case, maybe we can reduce/compress the image size to 30-150 KB at max.
2. Defer loading for scripts that are not immediately required when the page loads.
3. Serve static assets with an efficient cache policy. I'm not much sure about it, maybe if @gumaerc can share some thoughts on this?
4. Reduce/remove unused CSS/JS (if any)
5. Add explicit width and height for image elements.

Other than performance, `Accessibility`, `Best Practices` and `SEO` seems to be fine (90+ value) but `PWA` is not good. But I'm not sure if our goal is to make OCW a PWA? If yes, then I can look into it.

**Comment by gumaerc** [comment]
@MAbdurrehman12 The entire site is fronted by Fastly (including static assets) so that should be covered.  Because the entire thing is a static site, it's pushed up to S3 and then Fastly caches content as it's requested.

**Comment by MAbdurrehman12** [comment]
> @MAbdurrehman12 The entire site is fronted by Fastly (including static assets) so that should be covered. Because the entire thing is a static site, it's pushed up to S3 and then Fastly caches content as it's requested.

Thanks.
Do you also have some thoughts on the description of this [issue](https://github.com/mitodl/ocw-hugo-themes/issues/636)?

**Comment by pdpinch** [comment]
> The entire site is fronted by Fastly (including static assets) so that should be covered. Because the entire thing is a static site, it's pushed up to S3 and then Fastly caches content as it's requested.

@gumaerc I'm not sure which recommendation you're responding to. I started breaking them out into separate issues. Can you comment on them as appropriate?

**Comment by gumaerc** [comment]
@pdpinch Will do, but I was commenting on the item @MAbdurrehman12 tagged me in about caching specifically.  Essentially caching should already be covered because we front the entire site with Fastly, but you may want to ask devops for confirmation on how that works.

**Comment by pdpinch** [comment]
@MAbdurrehman12 won't finish this before he leaves
